"""agregando field para logs de pagos

Revision ID: 022aaa3c9a9b
Revises: e884e6ee48f5
Create Date: 2026-02-23 17:17:25.536115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022aaa3c9a9b'
down_revision: Union[str, Sequence[str], None] = 'e884e6ee48f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('PaymentTokenReference', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('PaymentId', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'PaymentId')
    op.drop_column('reservations', 'PaymentTokenReference')
    # ### end Alembic commands ###
