"""agregando campos finales de la reserva

Revision ID: 0cdb4a7196be
Revises: 1c2f4428e60a
Create Date: 2026-01-13 13:04:26.125472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0cdb4a7196be'
down_revision: Union[str, Sequence[str], None] = '1c2f4428e60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('roomTypeCode', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('ratePlanCode', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('adults', sa.Integer(), nullable=False))
    op.add_column('reservations', sa.Column('children', sa.Integer(), nullable=False))
    op.add_column('reservations', sa.Column('amountBeforeTax', sa.Float(), nullable=False))
    op.add_column('reservations', sa.Column('promoCode', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('specialRequests', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('guest_first_name', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('guest_last_name', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('guest_email', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('guest_phone', sa.String(length=255), nullable=False))
    op.drop_column('reservations', 'rateCode')
    op.drop_column('reservations', 'operaJson')
    op.drop_column('reservations', 'totalGuests')
    op.drop_column('reservations', 'nights')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('nights', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('totalGuests', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('operaJson', mysql.JSON(), nullable=False))
    op.add_column('reservations', sa.Column('rateCode', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('reservations', 'guest_phone')
    op.drop_column('reservations', 'guest_email')
    op.drop_column('reservations', 'guest_last_name')
    op.drop_column('reservations', 'guest_first_name')
    op.drop_column('reservations', 'specialRequests')
    op.drop_column('reservations', 'promoCode')
    op.drop_column('reservations', 'amountBeforeTax')
    op.drop_column('reservations', 'children')
    op.drop_column('reservations', 'adults')
    op.drop_column('reservations', 'ratePlanCode')
    op.drop_column('reservations', 'roomTypeCode')
    # ### end Alembic commands ###
