"""agregando mas campos para reservations

Revision ID: 1c2f4428e60a
Revises: 8e099acbaa5d
Create Date: 2026-01-12 18:15:35.760304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c2f4428e60a'
down_revision: Union[str, Sequence[str], None] = '8e099acbaa5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('confirmationNumber', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('reservationId', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('isPaid', sa.Boolean(), nullable=False))
    op.add_column('reservations', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('reservations', sa.Column('rateCode', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('operaJson', sa.JSON(), nullable=False))
    op.alter_column('reservations', 'checkIn',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reservations', 'checkOut',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'checkOut',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('reservations', 'checkIn',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.drop_column('reservations', 'operaJson')
    op.drop_column('reservations', 'rateCode')
    op.drop_column('reservations', 'createdAt')
    op.drop_column('reservations', 'isPaid')
    op.drop_column('reservations', 'reservationId')
    op.drop_column('reservations', 'confirmationNumber')
    # ### end Alembic commands ###
