"""agregando nuevos campos a la tabla de reservas v2

Revision ID: 4f2292de775c
Revises: 3d61c43ffc71
Create Date: 2026-01-14 10:24:57.064422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2292de775c'
down_revision: Union[str, Sequence[str], None] = '3d61c43ffc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('reservations', sa.Column('reservationId', sa.String(length=255), nullable=False))
    op.add_column('reservations', sa.Column('confirmationNumber', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'confirmationNumber')
    op.drop_column('reservations', 'reservationId')
    op.drop_column('reservations', 'createdAt')
    # ### end Alembic commands ###
