"""initial

Revision ID: e884e6ee48f5
Revises: 
Create Date: 2026-01-26 17:13:32.190021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e884e6ee48f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkIn', sa.String(length=255), nullable=False),
    sa.Column('checkOut', sa.String(length=255), nullable=False),
    sa.Column('roomTypeCode', sa.String(length=255), nullable=False),
    sa.Column('ratePlanCode', sa.String(length=255), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('amountBeforeTax', sa.Float(), nullable=False),
    sa.Column('promoCode', sa.String(length=255), nullable=False),
    sa.Column('specialRequests', sa.String(length=255), nullable=False),
    sa.Column('guest_first_name', sa.String(length=255), nullable=False),
    sa.Column('guest_last_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=255), nullable=False),
    sa.Column('isPaid', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('reservationId', sa.String(length=255), nullable=False),
    sa.Column('confirmationNumber', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
